<?xml version="1.0" encoding="utf-8"?><Database Name="IMS" Class="DataClasses4DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=IMS;Integrated Security=True" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="IMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Registration" Member="Registrations">
    <Type Name="Registration">
      <Column Name="customerid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="passwords" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>