<?xml version="1.0" encoding="utf-8"?><Database Name="IMS" Class="SportssDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=IMS;Integrated Security=True" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="IMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sports" Member="sports">
    <Type Name="sport">
      <Column Name="itemid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="itemname" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="descriptions" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="imagepath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>